version: '3.9'
services:
  cc_server:
    build: ./cc_server
    container_name: cc_server
    ports:
      - "5000:5000"
    tty: true
    stdin_open: true
    networks:
      - botnet
  bot:
    build: ./bot
    depends_on:
      - cc_server
    tty: true
    stdin_open: true
    networks:
      - botnet

networks:
  botnet:
    driver: bridge

