version: '3.9'
services:
  cc_server:
    build: ./cc_server
    container_name: cc_server
    ports:
      - "5000:5000"
    networks:
      - botnet
  bot:
    build: ./bot
    networks:
      - botnet

networks:
  botnet:
    driver: bridge

